python/Day16/django_user/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.edit, name="edit"),
    path('password/', views.chg_pwd, name="chg_pwd"),
    path('delete/', views.delete, name="delete"),
    path('follow/<int:u_id>/', views.follow, name="follow"),
    path('profile/<str:name>/', views.profile, name="profile"),
]

python/Day16/django_user/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

python/Day16/django_user/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from IPython import embed
from .forms import UserCustomChangeForm, UserCustomCreationForm
from django.contrib.auth import update_session_auth_hash as update_session
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


def signup(request):

    if request.user.is_authenticated:
        return redirect('boards:index')

    if request.method == "POST":
        # User model을 재설정해서 해당 폼을 사용할 수 없음.
        #그래서 새롭게 model을 설정한 폼으로 바꿈
        #form = UserCreationForm(request.POST)
        form = UserCustomCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('boards:index')
    else:
        #form = UserCreationForm()
        form = UserCustomCreationForm()
        #embed()
    context = {
        'form':form,
        'label':'회원가입'
    }

    return render(request, 'accounts/signup.html', context)

def login(request):

    if request.user.is_authenticated:
        return redirect('boards:index')


    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        #embed()
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'boards:index')

    else:
        form = AuthenticationForm()
    context = {
        'form':form,
        'label':'로그인'
    }

    # return render(request, 'accounts/auth_form.html', context)
    return render(request, 'accounts/login.html', context)

def logout(request):
    if request.method == "POST":
        auth_logout(request)
    return redirect('boards:index')

def edit(request):

    if request.method == "POST":
        form = UserCustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('boards:index')
    else:

    #form = UserChangeForm()
        form = UserCustomChangeForm(instance=request.user)
    context = {
        'form':form,
        'label':'회원정보수정'

    }

    return render(request, 'accounts/auth_form.html', context)

def chg_pwd(request):
    if request.method =="POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session(request, user)
            return redirect('accounts:adit')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
        'label':'비밀번호수정'
    }
    return render(request, 'accounts/auth_form.html', context)

def delete(request):
    if request.method == "POST":
        request.user.delete()

    return redirect('boards:index')

#Follow 로직 구현
@login_required
def follow(request, u_id):
    # 팔로우 할 우저 정보를 얻어옴.
    person = get_object_or_404(get_user_model(), id=u_id)

    #해당 유저 팔로우 목록에 접속한 유저가 있다면
    if person.followers.filter(id=request.user.id).exists():
        #팔로우 해제
        person.followers.remove(request.user)
    else:
        #팔로우
        person.followers.add(request.user)

    return redirect('boards:index')

def profile(request, name):
    person = get_object_or_404(get_user_model(), username=name)
    context = {
        'person':person
    }
    return render(request, 'accounts/profile.html', context)


    

python/Day16/django_user/accounts/templates/accounts/auth_form.html
{% extends 'base.html'%}
{% load bootstrap4%}
{% block body %}
<h1>{{ label }}</h1>


<form action='' method='POST'> 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% if request.resolver_match.url_name == "signup" %}
        {% buttons submit="회원가입"%}
        {% endbuttons %}
    {% elif request.resolver_match.url_name == "login" %}
        {% buttons submit="로그인"%}
        {% endbuttons %}
    {% elif request.resolver_match.url_name == "edit" %}
        {% buttons submit="회원정보수정"%}
        {% endbuttons %}
    {% else %}
        {% buttons submit="비밀번호수정"%}
        {% endbuttons %}
    {% endif %}
</form>


    {% if request.resolver_match.url_name == "edit" %}

        <form action="{% url 'accounts:delete' %}" method='POST'> 
                {% csrf_token %}
                <a href="#" onclick="this.parentNode.submit()">회원탈퇴</a>
        </form>
    {% endif %}       

</form>
{% endblock%}

python/Day16/django_user/accounts/templates/accounts/edit.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block body %}
<form action='' method='POST'> 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="수정하기"%}
    {% endbuttons%}
</form>

<form action="{% url 'accounts:delete' %}" method='POST'> 
    {% csrf_token %}
    <a href="#" onclick="this.parentNode.submit()">회원탈퇴</a>
</form>



{% endblock%}

python/Day16/django_user/accounts/templates/accounts/login.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% load socialaccount %}
{% block body %}
<form action='' method='POST'> 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="로그인"%}
    {% endbuttons %}
</form>
<a href="{% provider_login_url 'kakao' method='oauth2' %}" class="btn btn-warning">카카오 로그인</a>
<a href="{% provider_login_url 'naver' method='oauth2' %}" class="btn btn-success">네이버 로그인</a>
{% endblock%}

python/Day16/django_user/accounts/templates/accounts/profile.html
{% extends 'base.html'%}
{% block body %}
<div class="jumbotron text-center text-white bg-dark">
    <h1 class="display-4">{{ person.username }}님의 프로필</h1>
    <h4 class="border-white">
        <p class="lead">
            팔로워 : {{ person.followers.all|length }}
            팔로앙 : {{ person.followings.all|length }}
        </p>
        {% if user != person %}
            {% if user in person.followers.all %}
                <a href="{% url 'accounts:follow' person.id %}" class="btn btn-primary btn-lg">언팔로우</a>
            {% else %}
                <a href="{% url 'accounts:follow' person.id %}" class="btn btn-primary btn-lg">팔로우</a>
            {% endif %}
        
        {% endif %}
    </h4>
</div>
<hr>
<h3 class="text-cent">{{ person.username }}님이 작성한 글</h3>
<div class="row">
    {% for board in person.board_set.all %}
        <div class="col-4 my-2">
            <div class="card">
                <div class="card-body">
                    <blockquote class="blockquote">
                        <p class="mb-0">{{ com.board }}</p>
                        <footer class="blockquote-footer">{{ com.comment }}</footer>
                    </blockquote>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ board.title }}</h5>
                    <p class="card-text">{{ board.comment_set.all|length }}개의 댓글</p>
                    <p class="card-text">{{ board.like_users.all|length }} 하트</p>
                    <a href="{% url 'boards:detail' board.id %}" class="btn btn-primary">글로 가기</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock%}

python/Day16/django_user/accounts/templates/accounts/pwd.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block body %}

<form action='' method='POST'> 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="비밀번호 변경"%}
    {% endbuttons %}
</form>


{% endblock%}

python/Day16/django_user/accounts/templates/accounts/signup.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block body %}

<form action='' method='POST'> 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn=primary">회원가입</button>
    {% endbuttons %}

    <!--{#% buttons submit="회원가입2" reset="다시입력" %}
    {#% endbuttons %}

    <input type='submit'> -->

</form>


{% endblock%}