python/Day14/DJANGO_USER/boards/urls.py
from django.urls import path
from . import views

app_name='boards'
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('<int:b_id>/', views.detail, name="detail"),
    path('edit/<int:b_id>/', views.edit, name="edit"),
    path('delete/<int:b_id>/', views.delete, name="delete"),
]

python/Day14/DJANGO_USER/boards/models.py
from django.db import models
from django.conf import settings

class Board(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

python/Day14/DJANGO_USER/boards/forms.py
from django import forms
from .models import Board

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title','content']

python/Day14/DJANGO_USER/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BoardForm
from .models import Board
from django.contrib.auth.decorators import login_required

def index(request):
    boards = Board.objects.all()
    context={
        'boards':boards
    }
    return render(request,'boards/index.html',context)

@login_required #로그인 확인.2
def new(request):

    #login 확인.1
    # if request.user.is_authenticated:
    #     return redirect('boards:index')
    if request.method == "POST":
        form = BoardForm(request.POST) #data가 들어있는 form
        if form.is_valid(): #form 유효성 검사
            board = form.save(commit=False)
            board.user = request.user
            board.save()
            return redirect('boards:index')

    else:
        form = BoardForm()
        context = {
            'form':form
        }
        return render(request, 'boards/new.html', context)

def detail(request,b_id):
    board = get_object_or_404(Board, id=b_id) #있으면 가져오고 없으면 404에러 띄움
    context = {
        'board':board
    }
    return render(request, 'boards/detail.html', context)

def edit(request,b_id):
    board = get_object_or_404(Board, id=b_id)

    if request.user != board.user:
        return redirect('boards:index')

    if request.user == board.user:
        if request.method == "POST":
            form = BoardForm(request.POST, instance=board)
            if form.is_valid():
                board = form.save()
                return redirect('boards:detail', board.id)
        else:
            form = BoardForm(instance=board)
        context= {
            'form': form
        }
        return render(request, 'boards/edit.html', context)
        
def delete(request,b_id):
    board = get_object_or_404(Board, id=b_id)
    
    if request.user != board.user:
        return redirect('boards:index')

    if(request.method=="POST"):
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail',board.id)

python/Day14/DJANGO_USER/boards/templates/boards/detail.html
{% extends 'base.html' %}
{% block body %}
<table>
    <tr>
        <td>타이틀</td>
        <td>{{ board.title }}</td>
    </tr>
    <tr>
        <td>내용</td>
        <td>{{ board.content }}</td>
    </tr>
</table>

{% if user == board.user %}
<form action="{% url 'boards:delete' board.id %}" method='POST'>
    {% csrf_token %}
    <a href="{% url 'boards:edit' board.id %}">수정하기</a>
    <a href="#" onclick="this.parentNode.submit()">삭제하기</a>
</form>
{% endif %}

{% endblock %}

python/Day14/DJANGO_USER/boards/templates/boards/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<form action='' method='POST'>
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' value="수정하기">
</form>
{% endblock %}

python/Day14/DJANGO_USER/boards/templates/boards/index.html
{% extends 'base.html' %}
{% block body %}
<h1>index page</h1>

<ul>
    {% for board in boards %}
        <li><a href="{% url 'boards:detail' board.id %}">{{ board.title }}</a> - {{ board.user }}</li>
    {% endfor %}
</ul>

{% if user.is_authenticated %}
<a href="{% url 'boards:new' %}">New</a> <br>
{% else %}
<h3>로그인 해야 글을 작성할 수 있습니다.</h3>
{% endif %}

{% endblock %}

python/Day14/DJANGO_USER/boards/templates/boards/new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<form action='' method='POST'>
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' value="새글쓰기">
</form>

{% endblock %}